// AUTO-GENERATED by codegen/generate-events.mjs from Bloodbank schemas + publisher-events.json.
// Do not edit by hand — run `npm run codegen`.

export interface EventDataField {
  name: string;
  jsonType: string;
  required: boolean;
  description: string;
}

export interface EventSchema {
  type: string;
  domain: string;
  title: string;
  description: string;
  dataFields: EventDataField[];
}

export const eventSchemas: EventSchema[] = [
  {
    "type": "bloodbank.v1.agent.invocation.completed",
    "domain": "agent",
    "title": "Agent Invocation Completed Event",
    "description": "An agent invocation completed successfully. See bloodbank/docs/event-naming.md.",
    "dataFields": [
      {
        "name": "invocation_id",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "thread_id",
        "jsonType": "string",
        "required": false,
        "description": ""
      },
      {
        "name": "turn_id",
        "jsonType": "string",
        "required": false,
        "description": ""
      }
    ]
  },
  {
    "type": "bloodbank.v1.agent.invocation.failed",
    "domain": "agent",
    "title": "Agent Invocation Failed Event",
    "description": "An agent invocation terminated with a non-recoverable error. See bloodbank/docs/event-naming.md.",
    "dataFields": [
      {
        "name": "invocation_id",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "error_code",
        "jsonType": "string",
        "required": false,
        "description": ""
      },
      {
        "name": "error_message",
        "jsonType": "string",
        "required": false,
        "description": ""
      }
    ]
  },
  {
    "type": "bloodbank.v1.agent.invocation.started",
    "domain": "agent",
    "title": "Agent Invocation Started Event",
    "description": "An agent invocation began. One round of agent runtime calling an LLM. See bloodbank/docs/event-naming.md.",
    "dataFields": [
      {
        "name": "invocation_id",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "thread_id",
        "jsonType": "string",
        "required": false,
        "description": ""
      },
      {
        "name": "turn_id",
        "jsonType": "string",
        "required": false,
        "description": ""
      },
      {
        "name": "parent_invocation_id",
        "jsonType": "string",
        "required": false,
        "description": "Set on nested invocations (sub-agents)."
      }
    ]
  },
  {
    "type": "bloodbank.v1.agent.session.ended",
    "domain": "agent",
    "title": "Agent Session Ended Event",
    "description": "An agent CLI session ended. Canonical session-end event per bloodbank/docs/event-naming.md; supersedes cli.session.ended for agent CLIs.",
    "dataFields": [
      {
        "name": "session_id",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "end_reason",
        "jsonType": "string",
        "required": false,
        "description": ""
      }
    ]
  },
  {
    "type": "bloodbank.v1.agent.session.started",
    "domain": "agent",
    "title": "Agent Session Started Event",
    "description": "An agent CLI session began (claude, codex, copilot, …). Canonical session-start event per bloodbank/docs/event-naming.md; supersedes cli.session.started for agent CLIs.",
    "dataFields": [
      {
        "name": "session_id",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "working_directory",
        "jsonType": "string",
        "required": false,
        "description": ""
      }
    ]
  },
  {
    "type": "bloodbank.v1.agent.tool.completed",
    "domain": "agent",
    "title": "Agent Tool Completed Event",
    "description": "A tool call reached a terminal state. See bloodbank/docs/event-naming.md.",
    "dataFields": [
      {
        "name": "invocation_id",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "tool_call_id",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "tool_name",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "outcome",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "result",
        "jsonType": "string",
        "required": false,
        "description": "Tool result (open shape)."
      }
    ]
  },
  {
    "type": "bloodbank.v1.agent.tool.invoked",
    "domain": "agent",
    "title": "Agent Tool Invoked Event",
    "description": "A tool call was invoked by the runtime (mid-execution). See bloodbank/docs/event-naming.md.",
    "dataFields": [
      {
        "name": "invocation_id",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "tool_call_id",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "tool_name",
        "jsonType": "string",
        "required": true,
        "description": ""
      }
    ]
  },
  {
    "type": "bloodbank.v1.agent.tool.requested",
    "domain": "agent",
    "title": "Agent Tool Requested Event",
    "description": "An agent requested a tool call. The runtime has not executed it yet. See bloodbank/docs/event-naming.md.",
    "dataFields": [
      {
        "name": "invocation_id",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "tool_call_id",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "tool_name",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "arguments",
        "jsonType": "object",
        "required": false,
        "description": ""
      }
    ]
  },
  {
    "type": "bloodbank.v1.attendance.clock.clocked_in",
    "domain": "attendance",
    "title": "Attendance Clocked In Event",
    "description": "A worker was clocked in on a target timekeeping system. Orwell should emit this after a successful clock-in, whether triggered by a toggle or an explicit command.",
    "dataFields": [
      {
        "name": "clock_system",
        "jsonType": "string",
        "required": true,
        "description": "Timekeeping integration or system that accepted the clock-in, for example 'orwell'."
      },
      {
        "name": "principal",
        "jsonType": "string",
        "required": true,
        "description": "Logical worker or account identifier that is now clocked in."
      },
      {
        "name": "effective_at",
        "jsonType": "string",
        "required": true,
        "description": "Timestamp when the clock-in took effect according to the emitting system."
      },
      {
        "name": "source_command_id",
        "jsonType": "string",
        "required": false,
        "description": "command_id of the originating attendance command, if this event was caused by one."
      },
      {
        "name": "trigger",
        "jsonType": "string",
        "required": false,
        "description": "Which command form produced this event. Null if the system cannot determine it."
      }
    ]
  },
  {
    "type": "bloodbank.v1.attendance.clock.clocked_out",
    "domain": "attendance",
    "title": "Attendance Clocked Out Event",
    "description": "A worker was clocked out on a target timekeeping system. Orwell should emit this after a successful clock-out, whether triggered by a toggle or an explicit command.",
    "dataFields": [
      {
        "name": "clock_system",
        "jsonType": "string",
        "required": true,
        "description": "Timekeeping integration or system that accepted the clock-out, for example 'orwell'."
      },
      {
        "name": "principal",
        "jsonType": "string",
        "required": true,
        "description": "Logical worker or account identifier that is now clocked out."
      },
      {
        "name": "effective_at",
        "jsonType": "string",
        "required": true,
        "description": "Timestamp when the clock-out took effect according to the emitting system."
      },
      {
        "name": "source_command_id",
        "jsonType": "string",
        "required": false,
        "description": "command_id of the originating attendance command, if this event was caused by one."
      },
      {
        "name": "trigger",
        "jsonType": "string",
        "required": false,
        "description": "Which command form produced this event. Null if the system cannot determine it."
      }
    ]
  },
  {
    "type": "bloodbank.v1.attendance.clock.detected",
    "domain": "attendance",
    "title": "Attendance Clock State Detected Event",
    "description": "A target timekeeping system was queried and its current clock state was observed. Orwell should emit this after running a read-only state check.",
    "dataFields": [
      {
        "name": "clock_system",
        "jsonType": "string",
        "required": true,
        "description": "Timekeeping integration or system that was queried, for example 'orwell'."
      },
      {
        "name": "principal",
        "jsonType": "string",
        "required": true,
        "description": "Logical worker or account identifier whose clock state was observed."
      },
      {
        "name": "status",
        "jsonType": "string",
        "required": true,
        "description": "Derived current clock state at observation time."
      },
      {
        "name": "effective_at",
        "jsonType": "string",
        "required": true,
        "description": "Timestamp when the observation was made."
      },
      {
        "name": "source_command_id",
        "jsonType": "string",
        "required": false,
        "description": "command_id of the originating attendance.clock.request command, if this event was caused by one."
      },
      {
        "name": "today_row",
        "jsonType": "string",
        "required": false,
        "description": "Raw current-day timesheet row observed during detection, if available."
      },
      {
        "name": "button_texts",
        "jsonType": "array",
        "required": false,
        "description": "Visible clock-action button labels observed at detection time."
      },
      {
        "name": "failures",
        "jsonType": "array",
        "required": false,
        "description": "Portal failure hints observed while reading state, such as missing-punch errors."
      }
    ]
  },
  {
    "type": "bloodbank.v1.audio.file.received",
    "domain": "audio",
    "title": "Audio File Received Event",
    "description": "An audio file was observed appearing in a watched inbox directory (e.g. ~/audio/inbox). Producer is the inbox watcher. The same file_path may legitimately re-fire on re-detect/rescan; use ordering_key bucket 'file:<sha256(file_path)>' so de",
    "dataFields": [
      {
        "name": "file_path",
        "jsonType": "string",
        "required": true,
        "description": "Absolute path to the detected audio file on disk."
      },
      {
        "name": "file_name",
        "jsonType": "string",
        "required": false,
        "description": "Basename of the file, for convenience and display."
      },
      {
        "name": "inbox_dir",
        "jsonType": "string",
        "required": false,
        "description": "Absolute path of the inbox directory the watcher is observing."
      },
      {
        "name": "file_size_bytes",
        "jsonType": "integer",
        "required": false,
        "description": "Size of the file on disk in bytes at the time of detection."
      },
      {
        "name": "mime_type",
        "jsonType": "string",
        "required": false,
        "description": "Detected MIME type (e.g. 'audio/wav', 'audio/mpeg', 'audio/ogg', 'audio/x-m4a')."
      },
      {
        "name": "file_hash_sha256",
        "jsonType": "string",
        "required": false,
        "description": "SHA-256 hex digest of the file contents for dedup across re-detections."
      },
      {
        "name": "duration_seconds",
        "jsonType": "number",
        "required": false,
        "description": "Duration of the audio in seconds, if probeable at detect time."
      },
      {
        "name": "detected_at",
        "jsonType": "string",
        "required": false,
        "description": "RFC3339 timestamp when the watcher first observed the file. May differ from envelope.time if detection was queued."
      }
    ]
  },
  {
    "type": "bloodbank.v1.audio.transcription.completed",
    "domain": "audio",
    "title": "Audio Transcription Completed Event",
    "description": "A transcription job finished successfully and the transcript is available. For long transcripts the full text MAY be stored externally and referenced via transcript_uri instead of being inlined in transcript_text. Use ordering_key 'transcri",
    "dataFields": [
      {
        "name": "transcription_id",
        "jsonType": "string",
        "required": true,
        "description": "Same transcription_id as the originating started event."
      },
      {
        "name": "file_path",
        "jsonType": "string",
        "required": true,
        "description": "Absolute path of the audio file that was transcribed."
      },
      {
        "name": "transcript_text",
        "jsonType": "string",
        "required": true,
        "description": "Final transcript text. May be empty for silent or non-speech audio. Producers MAY truncate very long transcripts and rely on transcript_uri for the canonical full text."
      },
      {
        "name": "transcript_uri",
        "jsonType": "string",
        "required": false,
        "description": "Optional URI to the canonical full transcript (e.g. file://, s3://, https://). Use when transcript_text is too large to inline or has been truncated."
      },
      {
        "name": "language_detected",
        "jsonType": "string",
        "required": false,
        "description": "Engine-detected language as BCP-47 (e.g. 'en'). Null if not provided by the engine."
      },
      {
        "name": "duration_seconds",
        "jsonType": "number",
        "required": false,
        "description": "Duration of the audio in seconds."
      },
      {
        "name": "processing_seconds",
        "jsonType": "number",
        "required": false,
        "description": "Wall-clock time the engine spent transcribing in seconds."
      },
      {
        "name": "word_count",
        "jsonType": "integer",
        "required": false,
        "description": "Word count of transcript_text (or the canonical transcript when transcript_uri is set)."
      },
      {
        "name": "confidence",
        "jsonType": "number",
        "required": false,
        "description": "Aggregate engine confidence in [0,1]. Null if the engine does not report confidence."
      },
      {
        "name": "engine",
        "jsonType": "string",
        "required": false,
        "description": "Transcription engine that produced this result."
      },
      {
        "name": "engine_model",
        "jsonType": "string",
        "required": false,
        "description": "Specific model variant under the engine."
      },
      {
        "name": "segments",
        "jsonType": "array",
        "required": false,
        "description": "Optional time-aligned segments. Each item is {start_seconds, end_seconds, text, confidence?}. Producers MAY omit for cost; consumers MUST tolerate either shape."
      }
    ]
  },
  {
    "type": "bloodbank.v1.audio.transcription.failed",
    "domain": "audio",
    "title": "Audio Transcription Failed Event",
    "description": "A transcription job terminated with an error. Use this for any non-recoverable failure during the transcription pipeline (file unreadable, engine error, timeout, OOM, etc.). The 'retryable' flag tells downstream orchestrators whether re-iss",
    "dataFields": [
      {
        "name": "transcription_id",
        "jsonType": "string",
        "required": true,
        "description": "Same transcription_id as the originating started event (if one was emitted)."
      },
      {
        "name": "file_path",
        "jsonType": "string",
        "required": true,
        "description": "Absolute path of the audio file the failed job was operating on."
      },
      {
        "name": "error_code",
        "jsonType": "string",
        "required": false,
        "description": "Producer-defined short code (e.g. 'engine.timeout', 'file.unreadable', 'audio.unsupported_codec', 'engine.oom')."
      },
      {
        "name": "error_message",
        "jsonType": "string",
        "required": false,
        "description": "Human-readable error description."
      },
      {
        "name": "retryable",
        "jsonType": "boolean",
        "required": false,
        "description": "True when the orchestrator MAY safely re-issue the same audio.transcription.start command. False for permanent failures (e.g. corrupted file). Null when the producer cannot determine."
      },
      {
        "name": "engine",
        "jsonType": "string",
        "required": false,
        "description": "Transcription engine that failed."
      },
      {
        "name": "engine_model",
        "jsonType": "string",
        "required": false,
        "description": "Specific model variant under the engine."
      }
    ]
  },
  {
    "type": "bloodbank.v1.audio.transcription.started",
    "domain": "audio",
    "title": "Audio Transcription Started Event",
    "description": "A transcription job began. Emitted by the transcription service after it accepts a bloodbank.v1.audio.transcription.start command (or after it picks up a file.received event in autonomous mode). Use ordering_key 'transcription:<transcriptio",
    "dataFields": [
      {
        "name": "transcription_id",
        "jsonType": "string",
        "required": true,
        "description": "Unique identifier for this transcription job. Stable across started/completed/failed for the same job. Mirrors envelope.ordering_key bucket."
      },
      {
        "name": "file_path",
        "jsonType": "string",
        "required": true,
        "description": "Absolute path to the audio file being transcribed."
      },
      {
        "name": "command_id",
        "jsonType": "string",
        "required": false,
        "description": "command_id of the originating audio.transcription.start command. Null if started autonomously (e.g. watcher-driven without an explicit command)."
      },
      {
        "name": "engine",
        "jsonType": "string",
        "required": false,
        "description": "Transcription engine selected for this job (e.g. 'whisper', 'voxcpm2', 'elevenlabs')."
      },
      {
        "name": "engine_model",
        "jsonType": "string",
        "required": false,
        "description": "Specific model variant under the engine (e.g. 'whisper-large-v3', 'voxcpm2-base')."
      },
      {
        "name": "language",
        "jsonType": "string",
        "required": false,
        "description": "BCP-47 language hint provided to the engine (e.g. 'en', 'en-US', 'es'). Null means autodetect."
      }
    ]
  },
  {
    "type": "bloodbank.v1.cli.process.exited",
    "domain": "cli",
    "title": "Cli Process Exited Event",
    "description": "A CLI-spawned process terminated. See bloodbank/docs/event-naming.md.",
    "dataFields": [
      {
        "name": "session_id",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "process_id",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "exit_code",
        "jsonType": "integer",
        "required": true,
        "description": ""
      }
    ]
  },
  {
    "type": "bloodbank.v1.cli.process.spawned",
    "domain": "cli",
    "title": "Cli Process Spawned Event",
    "description": "An OS process was spawned within a CLI session. See bloodbank/docs/event-naming.md.",
    "dataFields": [
      {
        "name": "session_id",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "process_id",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "command",
        "jsonType": "array",
        "required": false,
        "description": "Argv of the spawned process."
      }
    ]
  },
  {
    "type": "bloodbank.v1.cli.session.ended",
    "domain": "cli",
    "title": "Cli Session Ended Event",
    "description": "A CLI session ended. See bloodbank/docs/event-naming.md.",
    "dataFields": [
      {
        "name": "session_id",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "end_reason",
        "jsonType": "string",
        "required": false,
        "description": ""
      }
    ]
  },
  {
    "type": "bloodbank.v1.cli.session.started",
    "domain": "cli",
    "title": "Cli Session Started Event",
    "description": "A CLI session began (e.g. claude or copilot process tree start). See bloodbank/docs/event-naming.md.",
    "dataFields": [
      {
        "name": "session_id",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "working_directory",
        "jsonType": "string",
        "required": false,
        "description": ""
      }
    ]
  },
  {
    "type": "bloodbank.v1.cli.stderr.appended",
    "domain": "cli",
    "title": "Cli Stderr Appended Event",
    "description": "A chunk of stderr was emitted by a CLI-spawned process. See bloodbank/docs/event-naming.md.",
    "dataFields": [
      {
        "name": "session_id",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "process_id",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "chunk",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "byte_offset",
        "jsonType": "integer",
        "required": false,
        "description": ""
      }
    ]
  },
  {
    "type": "bloodbank.v1.cli.stdout.appended",
    "domain": "cli",
    "title": "Cli Stdout Appended Event",
    "description": "A chunk of stdout was emitted by a CLI-spawned process. See bloodbank/docs/event-naming.md.",
    "dataFields": [
      {
        "name": "session_id",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "process_id",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "chunk",
        "jsonType": "string",
        "required": true,
        "description": "Verbatim stdout chunk text."
      },
      {
        "name": "byte_offset",
        "jsonType": "integer",
        "required": false,
        "description": "Cumulative byte offset within the process's stdout stream."
      }
    ]
  },
  {
    "type": "bloodbank.v1.conversation.message.appended",
    "domain": "conversation",
    "title": "Conversation Message Appended Event",
    "description": "A message was appended to the durable conversation transcript. See bloodbank/docs/event-naming.md.",
    "dataFields": [
      {
        "name": "thread_id",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "turn_id",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "message_id",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "role",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "text",
        "jsonType": "string",
        "required": false,
        "description": "Plaintext rendering of the message. May be omitted for privacy."
      }
    ]
  },
  {
    "type": "bloodbank.v1.conversation.thread.created",
    "domain": "conversation",
    "title": "Conversation Thread Created Event",
    "description": "A conversation thread was created. Emitted on the first turn of a new thread. See bloodbank/docs/event-naming.md.",
    "dataFields": [
      {
        "name": "thread_id",
        "jsonType": "string",
        "required": true,
        "description": "Stable thread identifier."
      }
    ]
  },
  {
    "type": "bloodbank.v1.conversation.thread.resumed",
    "domain": "conversation",
    "title": "Conversation Thread Resumed Event",
    "description": "A known conversation thread was reopened. See bloodbank/docs/event-naming.md.",
    "dataFields": [
      {
        "name": "thread_id",
        "jsonType": "string",
        "required": true,
        "description": ""
      }
    ]
  },
  {
    "type": "bloodbank.v1.conversation.turn.completed",
    "domain": "conversation",
    "title": "Conversation Turn Completed Event",
    "description": "A turn reached a terminal state. See bloodbank/docs/event-naming.md.",
    "dataFields": [
      {
        "name": "thread_id",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "turn_id",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "outcome",
        "jsonType": "string",
        "required": true,
        "description": "Terminal disposition of the turn."
      }
    ]
  },
  {
    "type": "bloodbank.v1.conversation.turn.started",
    "domain": "conversation",
    "title": "Conversation Turn Started Event",
    "description": "A new turn started inside a thread. The user prompt is what initiates a turn. See bloodbank/docs/event-naming.md.",
    "dataFields": [
      {
        "name": "thread_id",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "turn_id",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "prompt_text",
        "jsonType": "string",
        "required": false,
        "description": "Verbatim user prompt that initiated the turn. May be omitted for privacy."
      }
    ]
  },
  {
    "type": "bloodbank.v1.finance.account.detected",
    "domain": "finance",
    "title": "Finance Account Detected Event",
    "description": "Account auto-discovery inserted a new tracked account. Producer: tiller. See bloodbank/docs/event-naming.md.",
    "dataFields": [
      {
        "name": "account_id",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "name",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "institution",
        "jsonType": "string",
        "required": false,
        "description": ""
      },
      {
        "name": "class",
        "jsonType": "string",
        "required": false,
        "description": ""
      },
      {
        "name": "kind",
        "jsonType": "string",
        "required": false,
        "description": ""
      }
    ]
  },
  {
    "type": "bloodbank.v1.finance.paycheck.detected",
    "domain": "finance",
    "title": "Finance Paycheck Detected Event",
    "description": "An income deposit matching a payday pattern landed. Producer: tiller. See bloodbank/docs/event-naming.md.",
    "dataFields": [
      {
        "name": "txn_id",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "amount_cents",
        "jsonType": "integer",
        "required": true,
        "description": ""
      },
      {
        "name": "posted_on",
        "jsonType": "string",
        "required": false,
        "description": ""
      },
      {
        "name": "next_expected",
        "jsonType": "string",
        "required": false,
        "description": ""
      }
    ]
  },
  {
    "type": "bloodbank.v1.finance.projection.breached",
    "domain": "finance",
    "title": "Finance Projection Breached Event",
    "description": "The cashflow projection crossed a threshold (buffer dip, projected negative, or next-day bounce risk). Producer: tiller. See bloodbank/docs/event-naming.md.",
    "dataFields": [
      {
        "name": "min_cents",
        "jsonType": "integer",
        "required": false,
        "description": ""
      },
      {
        "name": "on_date",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "threshold_cents",
        "jsonType": "integer",
        "required": false,
        "description": ""
      },
      {
        "name": "horizon_days",
        "jsonType": "integer",
        "required": false,
        "description": ""
      },
      {
        "name": "item",
        "jsonType": "string",
        "required": false,
        "description": ""
      },
      {
        "name": "amount_cents",
        "jsonType": "integer",
        "required": false,
        "description": ""
      },
      {
        "name": "projected_cents",
        "jsonType": "integer",
        "required": false,
        "description": ""
      },
      {
        "name": "reason",
        "jsonType": "string",
        "required": false,
        "description": ""
      }
    ]
  },
  {
    "type": "bloodbank.v1.finance.subscription.canceled",
    "domain": "finance",
    "title": "Finance Subscription Canceled Event",
    "description": "A recurring series was confirmed dead (user-marked or auto-promoted after missed cycles). Producer: tiller. See bloodbank/docs/event-naming.md.",
    "dataFields": [
      {
        "name": "series_id",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "reclaimed_cents_per_month",
        "jsonType": "integer",
        "required": false,
        "description": ""
      },
      {
        "name": "missed_cycles",
        "jsonType": "integer",
        "required": false,
        "description": ""
      }
    ]
  },
  {
    "type": "bloodbank.v1.finance.subscription.detected",
    "domain": "finance",
    "title": "Finance Subscription Detected Event",
    "description": "The recurring detector found a new charge/income series. Producer: tiller. See bloodbank/docs/event-naming.md.",
    "dataFields": [
      {
        "name": "series_id",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "merchant",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "cadence",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "typical_cents",
        "jsonType": "integer",
        "required": false,
        "description": ""
      },
      {
        "name": "direction",
        "jsonType": "string",
        "required": false,
        "description": ""
      },
      {
        "name": "occurrences",
        "jsonType": "integer",
        "required": false,
        "description": ""
      }
    ]
  },
  {
    "type": "bloodbank.v1.finance.subscription.updated",
    "domain": "finance",
    "title": "Finance Subscription Updated Event",
    "description": "A recurring series changed state (status transition, cancel-watch checkpoint). Producer: tiller. See bloodbank/docs/event-naming.md.",
    "dataFields": [
      {
        "name": "series_id",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "from",
        "jsonType": "string",
        "required": false,
        "description": ""
      },
      {
        "name": "to",
        "jsonType": "string",
        "required": false,
        "description": ""
      },
      {
        "name": "overdue_by_days",
        "jsonType": "integer",
        "required": false,
        "description": ""
      }
    ]
  },
  {
    "type": "bloodbank.v1.finance.sync.completed",
    "domain": "finance",
    "title": "Finance Sync Completed Event",
    "description": "A tiller sync run finished with ingest/detector counts. Producer: tiller. See bloodbank/docs/event-naming.md.",
    "dataFields": [
      {
        "name": "run_id",
        "jsonType": "integer",
        "required": true,
        "description": ""
      },
      {
        "name": "status",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "trigger",
        "jsonType": "string",
        "required": false,
        "description": ""
      },
      {
        "name": "txns_seen",
        "jsonType": "integer",
        "required": false,
        "description": ""
      },
      {
        "name": "txns_inserted",
        "jsonType": "integer",
        "required": false,
        "description": ""
      },
      {
        "name": "txns_updated",
        "jsonType": "integer",
        "required": false,
        "description": ""
      },
      {
        "name": "balances_seen",
        "jsonType": "integer",
        "required": false,
        "description": ""
      },
      {
        "name": "balances_upserted",
        "jsonType": "integer",
        "required": false,
        "description": ""
      },
      {
        "name": "accounts_discovered",
        "jsonType": "integer",
        "required": false,
        "description": ""
      },
      {
        "name": "series_created",
        "jsonType": "integer",
        "required": false,
        "description": ""
      },
      {
        "name": "series_updated",
        "jsonType": "integer",
        "required": false,
        "description": ""
      },
      {
        "name": "zombies_detected",
        "jsonType": "integer",
        "required": false,
        "description": ""
      },
      {
        "name": "duration_ms",
        "jsonType": "integer",
        "required": false,
        "description": ""
      }
    ]
  },
  {
    "type": "bloodbank.v1.finance.sync.failed",
    "domain": "finance",
    "title": "Finance Sync Failed Event",
    "description": "A tiller sync run aborted. Producer: tiller. See bloodbank/docs/event-naming.md.",
    "dataFields": [
      {
        "name": "run_id",
        "jsonType": "integer",
        "required": true,
        "description": ""
      },
      {
        "name": "error",
        "jsonType": "string",
        "required": true,
        "description": ""
      }
    ]
  },
  {
    "type": "bloodbank.v1.finance.sync.started",
    "domain": "finance",
    "title": "Finance Sync Started Event",
    "description": "A tiller sheet-to-Postgres sync run opened. Producer: tiller. See bloodbank/docs/event-naming.md.",
    "dataFields": [
      {
        "name": "run_id",
        "jsonType": "integer",
        "required": true,
        "description": ""
      },
      {
        "name": "trigger",
        "jsonType": "string",
        "required": true,
        "description": ""
      }
    ]
  },
  {
    "type": "bloodbank.v1.finance.transaction.flagged",
    "domain": "finance",
    "title": "Finance Transaction Flagged Event",
    "description": "A transaction was flagged for review (by the operator or a rule such as large_unknown_charge). Producer: tiller. See bloodbank/docs/event-naming.md.",
    "dataFields": [
      {
        "name": "txn_id",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "reason",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "amount_cents",
        "jsonType": "integer",
        "required": false,
        "description": ""
      },
      {
        "name": "merchant",
        "jsonType": "string",
        "required": false,
        "description": ""
      },
      {
        "name": "posted_on",
        "jsonType": "string",
        "required": false,
        "description": ""
      },
      {
        "name": "by",
        "jsonType": "string",
        "required": false,
        "description": ""
      }
    ]
  },
  {
    "type": "bloodbank.v1.finance.transaction.recorded",
    "domain": "finance",
    "title": "Finance Transaction Recorded Event",
    "description": "A new posted transaction was ingested. Producer: tiller. See bloodbank/docs/event-naming.md.",
    "dataFields": [
      {
        "name": "txn_id",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "amount_cents",
        "jsonType": "integer",
        "required": true,
        "description": ""
      },
      {
        "name": "merchant",
        "jsonType": "string",
        "required": false,
        "description": ""
      },
      {
        "name": "posted_on",
        "jsonType": "string",
        "required": true,
        "description": ""
      }
    ]
  },
  {
    "type": "bloodbank.v1.finance.zombie_charge.detected",
    "domain": "finance",
    "title": "Finance Zombie Charge Detected Event",
    "description": "A charge landed on a series the owner already canceled — a zombie strike. Producer: tiller. See bloodbank/docs/event-naming.md.",
    "dataFields": [
      {
        "name": "series_id",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "txn_id",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "amount_cents",
        "jsonType": "integer",
        "required": true,
        "description": ""
      },
      {
        "name": "strike_count",
        "jsonType": "integer",
        "required": true,
        "description": ""
      },
      {
        "name": "total_stolen_cents",
        "jsonType": "integer",
        "required": false,
        "description": ""
      },
      {
        "name": "posted_on",
        "jsonType": "string",
        "required": false,
        "description": ""
      }
    ]
  },
  {
    "type": "bloodbank.v1.llm.request.sent",
    "domain": "llm",
    "title": "Llm Request Sent Event",
    "description": "A request was sent to an LLM provider. Protocol boundary. See bloodbank/docs/event-naming.md.",
    "dataFields": [
      {
        "name": "invocation_id",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "request_id",
        "jsonType": "string",
        "required": true,
        "description": ""
      }
    ]
  },
  {
    "type": "bloodbank.v1.llm.response.received",
    "domain": "llm",
    "title": "Llm Response Received Event",
    "description": "A response was received from an LLM provider. Protocol boundary. See bloodbank/docs/event-naming.md.",
    "dataFields": [
      {
        "name": "invocation_id",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "response_id",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "request_id",
        "jsonType": "string",
        "required": false,
        "description": "Pairing key for the originating request."
      }
    ]
  },
  {
    "type": "bloodbank.v1.repo.decision.recorded",
    "domain": "repo",
    "title": "Repo Decision Recorded Event",
    "description": "A PM agent recorded a repo-scoped decision. The repo slug belongs in data.repo, not in the CloudEvents type.",
    "dataFields": [
      {
        "name": "repo",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "decision",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "basis",
        "jsonType": "array",
        "required": false,
        "description": ""
      },
      {
        "name": "artifacts_root",
        "jsonType": "string",
        "required": false,
        "description": ""
      }
    ]
  },
  {
    "type": "bloodbank.v1.repo.intake.triaged",
    "domain": "repo",
    "title": "Repo Intake Triaged Event",
    "description": "A PM agent triaged an incoming repo-scoped request. The repo slug belongs in data.repo, not in the CloudEvents type.",
    "dataFields": [
      {
        "name": "repo",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "intake_id",
        "jsonType": "string",
        "required": false,
        "description": ""
      },
      {
        "name": "summary",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "requester",
        "jsonType": "string",
        "required": false,
        "description": ""
      },
      {
        "name": "priority",
        "jsonType": "string",
        "required": false,
        "description": ""
      }
    ]
  },
  {
    "type": "bloodbank.v1.repo.task.completed",
    "domain": "repo",
    "title": "Repo Task Completed Event",
    "description": "A PM/worker completed a repo-scoped task (ticket). The repo slug belongs in data.repo, not in the CloudEvents type.",
    "dataFields": [
      {
        "name": "repo",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "task_id",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "title",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "status",
        "jsonType": "string",
        "required": false,
        "description": ""
      },
      {
        "name": "completed_by",
        "jsonType": "string",
        "required": false,
        "description": ""
      },
      {
        "name": "completed_at",
        "jsonType": "string",
        "required": false,
        "description": ""
      },
      {
        "name": "resolution",
        "jsonType": "string",
        "required": false,
        "description": ""
      }
    ]
  },
  {
    "type": "bloodbank.v1.repo.task.created",
    "domain": "repo",
    "title": "Repo Task Created Event",
    "description": "A PM agent created a repo-scoped task. The repo slug belongs in data.repo, not in the CloudEvents type.",
    "dataFields": [
      {
        "name": "repo",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "task_id",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "title",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "description",
        "jsonType": "string",
        "required": false,
        "description": ""
      },
      {
        "name": "assignee",
        "jsonType": "string",
        "required": false,
        "description": ""
      }
    ]
  },
  {
    "type": "bloodbank.v1.repo.task.recorded",
    "domain": "repo",
    "title": "Repo Task Recorded Event",
    "description": "A PM/worker recorded a task (ticket) state update under the repo domain.",
    "dataFields": [
      {
        "name": "repo",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "task_id",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "title",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "change_kind",
        "jsonType": "string",
        "required": false,
        "description": "Type of update being recorded (status, assignee, priority, estimate, metadata, etc.)."
      },
      {
        "name": "from",
        "jsonType": "string",
        "required": false,
        "description": "Optional previous value/state."
      },
      {
        "name": "to",
        "jsonType": "string",
        "required": false,
        "description": "Optional new value/state."
      },
      {
        "name": "updated_by",
        "jsonType": "string",
        "required": false,
        "description": ""
      },
      {
        "name": "updated_at",
        "jsonType": "string",
        "required": false,
        "description": ""
      },
      {
        "name": "note",
        "jsonType": "string",
        "required": false,
        "description": ""
      }
    ]
  },
  {
    "type": "bloodbank.v1.system.heartbeat.received",
    "domain": "system",
    "title": "System Heartbeat Received Event",
    "description": "A liveness heartbeat was received from a producer. Also used as the canonical smoketest fixture. See bloodbank/docs/event-naming.md.",
    "dataFields": [
      {
        "name": "source_id",
        "jsonType": "string",
        "required": true,
        "description": "Identifier of the heartbeat producer (e.g. heartbeat-tick, smoketest)."
      },
      {
        "name": "sequence",
        "jsonType": "integer",
        "required": false,
        "description": "Monotonic counter from the producer."
      }
    ]
  },
  {
    "type": "bloodbank.v1.system.process.exited",
    "domain": "system",
    "title": "System Process Exited Event",
    "description": "A host-observed process or container terminated. Used by operator monitors such as docker-health-monitor to surface exit incidents into Bloodbank. See bloodbank/docs/event-naming.md.",
    "dataFields": [
      {
        "name": "source_id",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "runtime",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "resource_kind",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "container_name",
        "jsonType": "string",
        "required": false,
        "description": ""
      },
      {
        "name": "container_id",
        "jsonType": "string",
        "required": false,
        "description": ""
      },
      {
        "name": "image",
        "jsonType": "string",
        "required": false,
        "description": ""
      },
      {
        "name": "compose_project",
        "jsonType": "string",
        "required": false,
        "description": ""
      },
      {
        "name": "compose_service",
        "jsonType": "string",
        "required": false,
        "description": ""
      },
      {
        "name": "compose_file",
        "jsonType": "string",
        "required": false,
        "description": ""
      },
      {
        "name": "working_dir",
        "jsonType": "string",
        "required": false,
        "description": ""
      },
      {
        "name": "status",
        "jsonType": "string",
        "required": false,
        "description": ""
      },
      {
        "name": "exit_code",
        "jsonType": "integer",
        "required": false,
        "description": ""
      },
      {
        "name": "restart_policy",
        "jsonType": "string",
        "required": false,
        "description": ""
      },
      {
        "name": "finished_at",
        "jsonType": "string",
        "required": false,
        "description": ""
      },
      {
        "name": "started_at",
        "jsonType": "string",
        "required": false,
        "description": ""
      },
      {
        "name": "observed_at",
        "jsonType": "string",
        "required": false,
        "description": ""
      },
      {
        "name": "incident_summary",
        "jsonType": "string",
        "required": true,
        "description": ""
      },
      {
        "name": "expected_exit",
        "jsonType": "boolean",
        "required": true,
        "description": ""
      },
      {
        "name": "recovery_expected",
        "jsonType": "boolean",
        "required": true,
        "description": ""
      },
      {
        "name": "fingerprint",
        "jsonType": "string",
        "required": false,
        "description": ""
      }
    ]
  }
];
