#!/usr/bin/env node
// Generate src/nodes/Bloodbank/eventSchemas.ts from bloodbank/schemas/bloodbank/v1/**.
// This is what makes both publisher and consumer selections schema-backed: add
// or change a schema, run `npm run codegen` (or `npm run deploy`), and the event
// and command dropdowns update together.
import { readdirSync, readFileSync, writeFileSync, statSync, mkdirSync } from 'node:fs';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
// package: bloodbank/integrations/n8n-nodes-bloodbank/ ; schemas: bloodbank/schemas/bloodbank/v1
const schemasRoot = resolve(here, '..', '..', '..', 'schemas', 'bloodbank', 'v1');
const outFile = resolve(here, '..', 'src', 'nodes', 'Bloodbank', 'eventSchemas.ts');

function walk(dir) {
  const out = [];
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) out.push(...walk(p));
    else if (name.endsWith('.json')) out.push(p);
  }
  return out;
}

function scalarType(t) {
  if (Array.isArray(t)) t = t.find((x) => x !== 'null') || 'string';
  return t || 'string';
}

const schemas = [];
for (const file of walk(schemasRoot)) {
  let schema;
  try {
    schema = JSON.parse(readFileSync(file, 'utf8'));
  } catch {
    continue;
  }
  const props = schema.properties || {};
  const type = props.type && props.type.const;
  if (!type) continue;
  const kind = (props.kind && props.kind.const) || 'event';
  if (kind !== 'event' && kind !== 'command') continue;
  const domain = (props.domain && props.domain.const) || type.split('.')[2];
  const dataProps = (props.data && props.data.properties) || {};
  const dataRequired = (props.data && props.data.required) || [];
  const dataFields = Object.entries(dataProps).map(([name, def]) => ({
    name,
    jsonType: scalarType(def.type),
    required: dataRequired.includes(name),
    description: (def.description || '').replace(/\s+/g, ' ').trim().slice(0, 200),
  }));
  schemas.push({
    type,
    kind,
    domain,
    title: schema.title || type,
    description: (schema.description || '').replace(/\s+/g, ' ').trim().slice(0, 240),
    dataFields,
  });
}
schemas.sort((a, b) => a.type.localeCompare(b.type));

const banner =
  '// AUTO-GENERATED by codegen/generate-events.mjs from bloodbank/schemas/bloodbank/v1/**.\n' +
  '// Do not edit by hand — run `npm run codegen`.\n\n';
const iface =
  'export interface EventDataField {\n' +
  '  name: string;\n  jsonType: string;\n  required: boolean;\n  description: string;\n}\n\n' +
  'export interface EventSchema {\n' +
  "  type: string;\n  kind: 'event' | 'command';\n  domain: string;\n  title: string;\n  description: string;\n  dataFields: EventDataField[];\n}\n\n";
const body =
  'const schemas: EventSchema[] = ' + JSON.stringify(schemas, null, 2) + ';\n\n' +
  "export const eventSchemas = schemas.filter((schema) => schema.kind === 'event');\n" +
  "export const commandSchemas = schemas.filter((schema) => schema.kind === 'command');\n";

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, banner + iface + body);
const eventCount = schemas.filter((schema) => schema.kind === 'event').length;
const commandCount = schemas.filter((schema) => schema.kind === 'command').length;
console.log(`generated ${eventCount} events + ${commandCount} commands -> ${outFile}`);
