// AUTO-GENERATED by codegen/generate-events.mjs from the authorized repo.task JSON Schemas.
// Do not edit by hand — run `npm run codegen`. These are the only n8n events with
// production field-level validation; other authorized events retain legacy checks.

export type JsonValueType = 'array' | 'boolean' | 'integer' | 'null' | 'number' | 'object' | 'string';

export interface RepoTaskFieldContract {
  types: JsonValueType[];
  minLength?: number;
  enumValues?: unknown[];
  format?: string;
  pattern?: string;
}

export interface RepoTaskContract {
  sourceTimestampField: string | null;
  additionalProperties: boolean;
  required: string[];
  fields: Record<string, RepoTaskFieldContract>;
}

export const repoTaskContracts: Record<string, RepoTaskContract> = {
  "bloodbank.v1.repo.task.completed": {
    "sourceTimestampField": "completed_at",
    "additionalProperties": true,
    "required": [
      "repo",
      "task_id",
      "title"
    ],
    "fields": {
      "repo": {
        "types": [
          "string"
        ],
        "minLength": 1,
        "pattern": "^\\S+$"
      },
      "task_id": {
        "types": [
          "string"
        ],
        "minLength": 1,
        "pattern": "^\\S+$"
      },
      "title": {
        "types": [
          "string"
        ],
        "minLength": 1
      },
      "status": {
        "types": [
          "string"
        ],
        "enumValues": [
          "completed",
          "done",
          "closed"
        ]
      },
      "completed_by": {
        "types": [
          "string"
        ]
      },
      "completed_at": {
        "types": [
          "string"
        ],
        "format": "date-time"
      },
      "resolution": {
        "types": [
          "string"
        ]
      }
    }
  },
  "bloodbank.v1.repo.task.created": {
    "sourceTimestampField": null,
    "additionalProperties": true,
    "required": [
      "repo",
      "task_id",
      "title"
    ],
    "fields": {
      "repo": {
        "types": [
          "string"
        ],
        "minLength": 1,
        "pattern": "^\\S+$"
      },
      "task_id": {
        "types": [
          "string"
        ],
        "minLength": 1,
        "pattern": "^\\S+$"
      },
      "title": {
        "types": [
          "string"
        ],
        "minLength": 1
      },
      "description": {
        "types": [
          "string"
        ]
      },
      "assignee": {
        "types": [
          "string"
        ]
      }
    }
  },
  "bloodbank.v1.repo.task.recorded": {
    "sourceTimestampField": "updated_at",
    "additionalProperties": true,
    "required": [
      "repo",
      "task_id",
      "title"
    ],
    "fields": {
      "repo": {
        "types": [
          "string"
        ],
        "minLength": 1,
        "pattern": "^\\S+$"
      },
      "task_id": {
        "types": [
          "string"
        ],
        "minLength": 1,
        "pattern": "^\\S+$"
      },
      "title": {
        "types": [
          "string"
        ],
        "minLength": 1
      },
      "change_kind": {
        "types": [
          "string"
        ]
      },
      "from": {
        "types": [
          "string",
          "number",
          "boolean",
          "object",
          "array",
          "null"
        ]
      },
      "to": {
        "types": [
          "string",
          "number",
          "boolean",
          "object",
          "array",
          "null"
        ]
      },
      "updated_by": {
        "types": [
          "string"
        ]
      },
      "updated_at": {
        "types": [
          "string"
        ],
        "format": "date-time"
      },
      "note": {
        "types": [
          "string"
        ]
      }
    }
  }
};
