"""Recall sends the user's words, to the right banks, within its budget.

Pins the 2026-09-26 remediation (DeLoContainers
stacks/ai/hindsight/docs/2026-09-26-leverage-audit.md, plan item 1a/1b). That
day 62% of hub recall queries were harness XML or slash commands, 111 were
rejected as "Query too long", 321 were abandoned mid-rerank (250 of them on the
general/infra fan-out), and each prompt waited ~6.5s for the attempt.
"""
from __future__ import annotations

import http.server
import json
import os
import sys
import tempfile
import threading
import time
import unittest
from pathlib import Path
from unittest import mock

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import hindsight


class CleanupTests(unittest.TestCase):
    def test_a_task_notification_is_not_a_question(self):
        prompt = ("<task-notification>\n<task-id>bu11</task-id>\n<tool-use-id>toolu_1</tool-use-id>\n"
                  "<output-file>/tmp/x</output-file>\n<status>completed</status>\n"
                  "<summary>Background command \"run tests\" completed (exit code 0)</summary>\n"
                  "</task-notification>\nRead the output file to retrieve the result: /tmp/x")
        self.assertEqual(hindsight.clean_query(prompt), "")

    def test_system_reminders_are_dropped_and_the_user_kept(self):
        prompt = ("<system-reminder>\n# Environment update\n - Additional working directories added\n"
                  "</system-reminder>\nHow does the hook hub pick which banks to recall from?")
        self.assertEqual(hindsight.clean_query(prompt), "How does the hook hub pick which banks to recall from?")

    def test_a_raw_slash_command_keeps_its_arguments(self):
        self.assertEqual(hindsight.clean_query("/review-pr 123 please look at the retry logic"),
                         "123 please look at the retry logic")
        self.assertEqual(hindsight.clean_query("/plugin:skill-name   trailing args here"), "trailing args here")

    def test_a_rendered_slash_command_keeps_only_its_arguments(self):
        prompt = ("<command-message>bmad-build-auto</command-message>\n"
                  "<command-name>/bmad-build-auto</command-name>\n"
                  "<command-args>4-1-hosted-auth story, focus on the refresh token path</command-args>")
        self.assertEqual(hindsight.clean_query(prompt), "4-1-hosted-auth story, focus on the refresh token path")

    def test_a_leading_path_is_not_a_slash_command(self):
        prompt = "/home/me/code/foo/bar.py throws KeyError on startup"
        self.assertEqual(hindsight.clean_query(prompt), prompt)

    def test_local_command_output_and_caveats_are_dropped(self):
        prompt = ("<local-command-caveat>Caveat: The messages below were generated by the user while running "
                  "local commands.</local-command-caveat>\n"
                  "<local-command-stdout>Set effort level to xhigh</local-command-stdout>")
        self.assertEqual(hindsight.clean_query(prompt), "")

    def test_codex_and_teammate_frames_are_dropped(self):
        for prompt in (
            '<send_user_message_question_reply> [{"answer":"Phone","question":"Where?"}] </send_user_message_question_reply>',
            'Another Claude session sent a message: <teammate-message teammate_id="impl" color="blue"> '
            '{"type":"idle_notification"} </teammate-message>',
            "<environment_context>\n  <cwd>/x</cwd>\n</environment_context>",
            "<turn_aborted> The user interrupted the previous turn on purpose. </turn_aborted>",
            "This session is being continued from a previous conversation that ran out of context. Summary...",
        ):
            self.assertEqual(hindsight.clean_query(prompt), "", prompt)

    def test_an_unknown_kebab_wrapper_opening_a_line_is_a_harness_frame(self):
        prompt = "<foo-bar id=\"1\">\nharness payload\n</foo-bar>\nplease fix the flaky receipts test"
        self.assertEqual(hindsight.clean_query(prompt), "please fix the flaky receipts test")

    def test_inline_html_the_user_typed_survives(self):
        prompt = "why doesn't my <button>Click me</button> render inside the modal?"
        self.assertEqual(hindsight.clean_query(prompt), prompt)

    def test_pasted_content_is_the_users_own(self):
        prompt = "look at dumply's hooks.\n<pasted_content id=\"0f54\">the logs say ERROR 42</pasted_content>"
        self.assertEqual(hindsight.clean_query(prompt), "look at dumply's hooks. the logs say ERROR 42")

    def test_whitespace_is_collapsed(self):
        self.assertEqual(hindsight.clean_query("  why\n\n\tis   this slow?  "), "why is this slow?")


class TruncationTests(unittest.TestCase):
    def setUp(self):
        # The hub's interpreter has no tiktoken; pin the char path either way.
        patcher = mock.patch.object(hindsight, "_ENCODER", None)
        patcher.start()
        self.addCleanup(patcher.stop)

    def test_a_short_query_is_untouched(self):
        self.assertEqual(hindsight.cap_query("why is recall slow"), "why is recall slow")

    def test_a_long_query_keeps_its_head_and_tail_under_the_cap(self):
        text = "Fix the failing deploy. " + "noise 0xdeadbeef /var/lib/x " * 400 + "What is the root cause?"
        capped = hindsight.cap_query(text)
        self.assertLessEqual(len(capped), 1000)
        self.assertTrue(capped.startswith("Fix the failing deploy."))
        self.assertTrue(capped.endswith("What is the root cause?"))
        self.assertIn(hindsight.ELISION, capped)

    def test_the_char_cap_is_configurable(self):
        with mock.patch.dict(os.environ, {"HINDSIGHT_RECALL_QUERY_MAX_CHARS": "200"}):
            self.assertLessEqual(len(hindsight.cap_query("word " * 500)), 200)

    def test_halving_halves(self):
        text = hindsight.cap_query("alpha beta gamma delta " * 200)
        self.assertLessEqual(len(hindsight.halve_query(text)), len(text) // 2 + 1)

    def test_the_token_path_is_used_when_an_encoder_exists(self):
        class Words:
            def encode(self, text, disallowed_special=()):
                return text.split()

            def decode(self, ids):
                return " ".join(ids)

        with mock.patch.object(hindsight, "_ENCODER", Words()):
            capped = hindsight.cap_query(" ".join(f"w{i}" for i in range(1000)))
        self.assertLessEqual(len(capped.split()), 401)
        self.assertTrue(capped.startswith("w0 ") and capped.endswith(" w999"))


class BankSelectionTests(unittest.TestCase):
    def setUp(self):
        self.temporary = tempfile.TemporaryDirectory()
        self.addCleanup(self.temporary.cleanup)
        self.root = Path(self.temporary.name)
        clean = {key: value for key, value in os.environ.items()
                 if key not in {"HINDSIGHT_GLOBAL_BANKS", "HINDSIGHT_RECALL_GENERAL", "HINDSIGHT_ANCESTRY",
                                "HINDSIGHT_FANOUT", "HERMES_HOME", "HINDSIGHT_RECALL_MAX_BANKS"}}
        patcher = mock.patch.dict(os.environ, clean, clear=True)
        patcher.start()
        self.addCleanup(patcher.stop)
        checkout = mock.patch.object(hindsight, "main_checkout", return_value=self.root)
        checkout.start()
        self.addCleanup(checkout.stop)

    def test_the_default_sync_path_is_the_primary_bank_only(self):
        self.assertEqual(hindsight.recall_banks("claude", "bloodbank"), ["bloodbank"])

    def test_general_and_global_banks_are_opt_in(self):
        with mock.patch.dict(os.environ, {"HINDSIGHT_RECALL_GENERAL": "1", "HINDSIGHT_GLOBAL_BANKS": "infra docker"}):
            self.assertEqual(hindsight.recall_banks("claude", "bloodbank"), ["bloodbank", "general", "infra", "docker"])

    def test_a_repo_can_add_banks_from_its_main_checkout(self):
        (self.root / ".hindsight").mkdir()
        (self.root / ".hindsight/recall-banks").write_text("# infra-flavored repo\ninfra\n\ndocker  # containers\n")
        self.assertEqual(hindsight.repo_recall_banks(), ["infra", "docker"])
        self.assertEqual(hindsight.recall_banks("claude", "DeLoContainers"), ["DeLoContainers", "infra", "docker"])

    def test_the_repo_list_never_duplicates_the_primary(self):
        (self.root / ".hindsight").mkdir()
        (self.root / ".hindsight/recall-banks").write_text("bloodbank\ninfra\n")
        self.assertEqual(hindsight.recall_banks("claude", "bloodbank"), ["bloodbank", "infra"])

    def test_fan_out_is_opt_in(self):
        graph = self.root / "graph.json"
        graph.write_text(json.dumps({"graph": {"bloodbank": [{"bank": "33GOD", "score": 0.9}]}}))
        with mock.patch.dict(os.environ, {"HINDSIGHT_DREAM_GRAPH": str(graph)}):
            self.assertEqual(hindsight.recall_banks("claude", "bloodbank"), ["bloodbank"])
            with mock.patch.dict(os.environ, {"HINDSIGHT_FANOUT": "1"}):
                self.assertEqual(hindsight.recall_banks("claude", "bloodbank"), ["bloodbank", "33GOD"])


class MainCheckoutTests(unittest.TestCase):
    def test_a_worktree_resolves_to_its_primary_checkout(self):
        with mock.patch.object(hindsight, "repository", return_value=Path("/w/feature")), \
             mock.patch.object(hindsight.subprocess, "run", return_value=mock.Mock(returncode=0, stdout="/code/repo/.git\n")):
            self.assertEqual(hindsight.main_checkout(), Path("/code/repo"))

    def test_a_submodule_resolves_to_its_own_toplevel(self):
        with mock.patch.object(hindsight, "repository", return_value=Path("/code/super/sub")), \
             mock.patch.object(hindsight.subprocess, "run",
                               return_value=mock.Mock(returncode=0, stdout="/code/super/.git/modules/sub\n")):
            self.assertEqual(hindsight.main_checkout(), Path("/code/super/sub"))


FAKE_CLI = r'''#!/usr/bin/env python3
import json, os, sys, time
from pathlib import Path
args = sys.argv[1:]
bank, query = args[2], args[3]
with Path(os.environ["CALL_LOG"]).open("a") as f:
    f.write(json.dumps({"bank": bank, "query": query, "pid": os.getpid(), "args": args}) + "\n")
if bank == "slow":
    time.sleep(30)
if bank == "picky" and len(query) > int(os.environ.get("PICKY_MAX", "200")):
    sys.stderr.write("✗ Request rejected (400)\n\nServer response:\n  API request failed (400 Bad Request): "
                     '{"detail":"Query too long: 600 tokens exceeds maximum of 500. Please shorten your query."}\n')
    raise SystemExit(1)
if bank == "dense" and 3 * len(query) > 500:
    sys.stderr.write("✗ Request rejected (400)\n\nServer response:\n  API request failed (400 Bad Request): "
                     '{"detail":"Query too long: %d tokens exceeds maximum of 500. Please shorten your query."}\n'
                     % (3 * len(query)))
    raise SystemExit(1)
if bank == "broken":
    sys.stderr.write("connection refused\n")
    raise SystemExit(1)
if bank == "void":
    print(json.dumps({"results": []}))
    raise SystemExit(0)
print(json.dumps({"results": [{"text": f"fact from {bank}"}]}))
'''


class BoundedRecallTests(unittest.TestCase):
    def setUp(self):
        self.temporary = tempfile.TemporaryDirectory()
        self.addCleanup(self.temporary.cleanup)
        self.root = Path(self.temporary.name)
        self.calls = self.root / "calls.jsonl"
        fake = self.root / "hindsight"
        fake.write_text(FAKE_CLI)
        fake.chmod(0o700)
        patcher = mock.patch.dict(os.environ, {
            "HINDSIGHT_BIN": str(fake), "HS_JOURNAL_DIR": str(self.root / "journal"),
            "CALL_LOG": str(self.calls), "BB_HOOK_INVOCATION_ID": "t"})
        patcher.start()
        self.addCleanup(patcher.stop)
        self.addCleanup(mock.patch.stopall)
        self.bank = mock.patch.object(hindsight, "bank", return_value="fast").start()
        self.banks = mock.patch.object(hindsight, "recall_banks", return_value=["fast"]).start()

    def calls_made(self):
        return [json.loads(line) for line in self.calls.read_text().splitlines()] if self.calls.exists() else []

    def journal(self, session="s"):
        path = self.root / "journal/sessions" / f"claude-{session}.jsonl"
        return [json.loads(line) for line in path.read_text().splitlines()]

    def test_the_deadline_kills_a_stalled_bank_and_keeps_what_finished(self):
        self.banks.return_value = ["fast", "slow"]
        started = time.monotonic()
        with mock.patch.dict(os.environ, {"HINDSIGHT_RECALL_TIMEOUT": "1.0"}):
            output = hindsight.recall({"session_id": "s", "prompt": "how does the hub dispatch sync handlers?"},
                                      "claude", "UserPromptSubmit")
        elapsed = time.monotonic() - started
        self.assertLess(elapsed, 2.0, "the handler must return at its deadline, not when the slowest bank does")
        self.assertEqual(output["_hook_hub"]["reason"], "recall_partial")
        context = json.loads(output["stdout"])["hookSpecificOutput"]["additionalContext"]
        self.assertIn("fact from fast", context)
        slow_pid = next(call["pid"] for call in self.calls_made() if call["bank"] == "slow")
        time.sleep(0.1)
        with self.assertRaises(ProcessLookupError, msg="the stalled CLI must be killed, not orphaned"):
            os.kill(slow_pid, 0)
        per_bank = {row["bank"]: row for row in self.journal()[-1]["per_bank"]}
        self.assertEqual(per_bank["fast"]["status"], "ok")
        self.assertEqual(per_bank["slow"]["status"], "timeout")
        # Bounded by the deadline (measured from process start), never by the 30s sleep.
        self.assertLess(per_bank["slow"]["latency_ms"], 1500)

    def test_a_query_too_long_is_retried_once_at_half_length(self):
        self.banks.return_value = ["picky"]
        with mock.patch.dict(os.environ, {"PICKY_MAX": "300", "HINDSIGHT_RECALL_QUERY_MAX_CHARS": "500"}), \
             mock.patch.object(hindsight, "_ENCODER", None):
            output = hindsight.recall({"session_id": "s", "prompt": "please explain " + "the retry path " * 100},
                                      "claude", "UserPromptSubmit")
        queries = [len(call["query"]) for call in self.calls_made()]
        self.assertEqual(len(queries), 2)
        self.assertLessEqual(queries[1], queries[0] // 2 + 1)
        self.assertEqual(output["_hook_hub"]["status"], "succeeded")
        row = self.journal()[-1]["per_bank"][0]
        self.assertEqual((row["status"], row.get("retried")), ("ok", True))

    def test_a_dense_query_is_cut_to_the_servers_own_count(self):
        # Emoji, braille and block-drawing pastes run ~3 cl100k tokens a char:
        # half of the 1,000-char cap is still ~1,500 tokens, so halving alone
        # would be rejected twice and the prompt would get no memory at all.
        self.banks.return_value = ["dense"]
        with mock.patch.object(hindsight, "_ENCODER", None):
            output = hindsight.recall({"session_id": "s", "prompt": "why does the load graph look like this "
                                       + "⣿⣷⣶⣤⣀ " * 400}, "claude", "UserPromptSubmit")
        queries = [call["query"] for call in self.calls_made()]
        self.assertEqual(len(queries), 2)
        self.assertLessEqual(3 * len(queries[1]), 500)
        self.assertTrue(queries[1].startswith("why does the load graph"))
        self.assertEqual(output["_hook_hub"]["status"], "succeeded")
        row = self.journal()[-1]["per_bank"][0]
        self.assertEqual((row["status"], row.get("retried")), ("ok", True))

    def test_a_persistent_400_is_journaled_as_http_400(self):
        self.banks.return_value = ["picky"]
        with mock.patch.dict(os.environ, {"PICKY_MAX": "10"}):
            output = hindsight.recall({"session_id": "s", "prompt": "please explain the retry path in the publisher"},
                                      "claude", "UserPromptSubmit")
        row = self.journal()[-1]["per_bank"][0]
        self.assertEqual(row["status"], "http_400")
        self.assertIn("Query too long", row["detail"])
        self.assertEqual(output["_hook_hub"]["reason"], "recall_query_rejected")

    def test_every_bank_outcome_is_journaled(self):
        self.banks.return_value = ["fast", "void", "broken"]
        prompt = "<system-reminder>noise</system-reminder>\nhow does the hub journal recall outcomes per bank?"
        hindsight.recall({"session_id": "s", "prompt": prompt}, "claude", "UserPromptSubmit")
        event = self.journal()[-1]
        self.assertEqual(event["event"], "recall")
        self.assertEqual(event["query_len_raw"], len(prompt))
        self.assertEqual(event["query_len_clean"], len("how does the hub journal recall outcomes per bank?"))
        self.assertEqual(event["query_len_sent"], event["query_len_clean"])
        statuses = {row["bank"]: row["status"] for row in event["per_bank"]}
        self.assertEqual(statuses, {"fast": "ok", "void": "empty", "broken": "error"})
        for row in event["per_bank"]:
            self.assertIn("latency_ms", row)
            self.assertIn("results", row)
        self.assertEqual(event["failed_banks"], 1)
        self.assertTrue(event["returned_anything"])

    def test_the_query_sent_is_the_cleaned_one(self):
        hindsight.recall({"session_id": "s", "prompt": "/bmad-build-auto story 4-1 hosted auth refresh path"},
                         "claude", "UserPromptSubmit")
        self.assertEqual(self.calls_made()[0]["query"], "story 4-1 hosted auth refresh path")

    def test_a_harness_only_prompt_is_skipped_and_journaled(self):
        prompt = "<task-notification><task-id>x</task-id><status>completed</status></task-notification>"
        output = hindsight.recall({"session_id": "s", "prompt": prompt}, "claude", "UserPromptSubmit")
        self.assertEqual(output["_hook_hub"], {"status": "skipped", "reason": "query_under_min_length_after_cleanup",
                                               "exit_code": 0})
        self.assertEqual(self.calls_made(), [])
        event = self.journal()[-1]
        self.assertEqual((event["event"], event["reason"], event["query_len_clean"]),
                         ("recall_skipped", "query_under_min_length_after_cleanup", 0))


class _Models(http.server.BaseHTTPRequestHandler):
    models: dict[str, tuple[int, dict]] = {}
    delay = 0.0
    seen: list[str] = []

    def do_GET(self):  # noqa: N802
        type(self).seen.append(self.headers.get("Authorization", ""))
        time.sleep(type(self).delay)
        model = self.path.rsplit("/", 1)[-1]
        code, body = type(self).models.get(model, (404, {"detail": f"Mental model '{model}' not found"}))
        data = json.dumps(body).encode()
        self.send_response(code)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(data)))
        self.end_headers()
        self.wfile.write(data)

    def log_message(self, *args):
        pass


class BriefingTests(unittest.TestCase):
    def setUp(self):
        self.server = http.server.ThreadingHTTPServer(("127.0.0.1", 0), _Models)
        threading.Thread(target=self.server.serve_forever, daemon=True).start()
        self.addCleanup(self.server.server_close)
        self.addCleanup(self.server.shutdown)
        _Models.delay = 0.0
        _Models.seen = []
        _Models.models = {
            "briefing": (200, {"id": "briefing", "name": "Project Briefing", "content": "Bloodbank is the event bus."}),
            "rules": (200, {"id": "rules", "name": "Conventions", "content": "Conventions: Generating content..."}),
        }
        self.temporary = tempfile.TemporaryDirectory()
        self.addCleanup(self.temporary.cleanup)
        config = Path(self.temporary.name) / "config"
        config.write_text(f'api_url = "http://127.0.0.1:{self.server.server_port}"\napi_key = "from-config"\n')
        patcher = mock.patch.dict(os.environ, {"HINDSIGHT_CONFIG": str(config),
                                               "HS_JOURNAL_DIR": str(Path(self.temporary.name) / "journal")})
        patcher.start()
        self.addCleanup(patcher.stop)
        for name in ("HINDSIGHT_API_URL", "HINDSIGHT_API_KEY"):
            os.environ.pop(name, None)
        bank = mock.patch.object(hindsight, "bank", return_value="bloodbank")
        bank.start()
        self.addCleanup(bank.stop)

    def test_ready_models_are_injected_and_missing_or_pending_ones_skipped(self):
        output = hindsight.briefing({"session_id": "b", "source": "startup"}, "claude", "SessionStart")
        self.assertEqual(output["_hook_hub"]["reason"], "briefing_injected")
        context = json.loads(output["stdout"])["hookSpecificOutput"]
        self.assertEqual(context["hookEventName"], "SessionStart")
        text = context["additionalContext"]
        self.assertIn("# Hindsight briefing: bank `bloodbank`", text)
        self.assertIn("## Project Briefing", text)
        self.assertIn("Bloodbank is the event bus.", text)
        self.assertNotIn("Generating content", text)
        self.assertEqual(set(_Models.seen), {"Bearer from-config"}, "the key comes from ~/.hindsight/config")
        journal = Path(os.environ["HS_JOURNAL_DIR"]) / "sessions/claude-b.jsonl"
        event = json.loads(journal.read_text().splitlines()[-1])
        self.assertEqual(event["models"], {"briefing": "ok", "pitfalls": "not_found", "rules": "pending"})

    def test_nothing_ready_is_a_silent_skip(self):
        _Models.models = {}
        output = hindsight.briefing({"session_id": "b"}, "claude", "SessionStart")
        self.assertEqual((output["_hook_hub"]["status"], output["stdout"]), ("skipped", ""))

    def test_a_slow_api_never_blocks_the_session(self):
        _Models.delay = 2.0
        with mock.patch.dict(os.environ, {"HINDSIGHT_BRIEFING_TIMEOUT": "0.3"}):
            started = time.monotonic()
            output = hindsight.briefing({"session_id": "b"}, "claude", "SessionStart")
        self.assertLess(time.monotonic() - started, 1.0)
        self.assertEqual(output["_hook_hub"]["reason"], "no_briefing_models")

    def test_an_unreachable_api_is_a_silent_skip(self):
        Path(os.environ["HINDSIGHT_CONFIG"]).write_text('api_url = "http://127.0.0.1:9"\napi_key = "k"\n')
        output = hindsight.briefing({"session_id": "b"}, "claude", "SessionStart")
        self.assertEqual(output["_hook_hub"]["status"], "skipped")

    def test_a_resumed_session_is_not_briefed_twice(self):
        output = hindsight.briefing({"session_id": "b", "source": "resume"}, "claude", "SessionStart")
        self.assertEqual(output["_hook_hub"]["reason"], "session_resumed")
        self.assertEqual(_Models.seen, [])

    def test_the_briefing_is_capped(self):
        _Models.models = {name: (200, {"name": name.title(), "content": "x " * 20000})
                          for name in hindsight.BRIEFING_MODELS}
        with mock.patch.dict(os.environ, {"HINDSIGHT_BRIEFING_MAX_CHARS": "3000"}):
            output = hindsight.briefing({"session_id": "b"}, "claude", "SessionStart")
        self.assertLess(len(json.loads(output["stdout"])["hookSpecificOutput"]["additionalContext"]), 3600)


class CliOutputTests(unittest.TestCase):
    """Pinned against the 0.10.1 CLI's real stderr (2026-09-26)."""

    NOT_FOUND = "✗ Not found (404): Bank 'zz' not found\n\nAPI URL:\n  https://api.hs.delo.sh\n"
    TOO_LONG = ("✗ Request rejected (400)\n\nAPI URL:\n  https://api.hs.delo.sh\n\nServer response:\n"
                "  Query too long: 1051 tokens exceeds maximum of 500. Please shorten your query.\n")

    def test_a_never_created_bank_is_not_found_and_says_why(self):
        self.assertEqual(hindsight.classify(1, "", self.NOT_FOUND), ("not_found", []))
        self.assertEqual(hindsight._detail("", self.NOT_FOUND), "Not found (404): Bank 'zz' not found")

    def test_a_rejected_query_reports_the_server_body(self):
        self.assertEqual(hindsight.classify(1, "", self.TOO_LONG)[0], "http_400")
        self.assertTrue(hindsight._detail("", self.TOO_LONG).startswith("Query too long: 1051 tokens"))


if __name__ == "__main__":
    unittest.main()
